### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by ehnwebmaster** [borestad/blocklist-abuseipdb#6]
Hello,

What about filtering the Ip's by categories?

For example

A list with DDoS reported Ip's (category 4)

https://www.abuseipdb.com/categories

Thank you in advance

**Comment by borestad** [comment]
Hi! Unfortunately AbuseIPDB does not expose that information via their API. The data retrieved looks like this:

...
64.23.182.34
43.163.229.92
43.156.236.44
43.156.79.21
89.252.169.173
49.51.187.152
43.134.20.26
218.92.0.97
...

...without any way of distinguish them. There might be usecases for this, but since this list has such high accuracy without false positives, it is considered a `route to /dev/null`

Providing more statistics might be possible though. If so, is there anything in particular that would be interesting to know?

**Comment by ehnwebmaster** [comment]
You're right, is not possible to do with AbuseIPDB. Will contact with them to suggest add this feature, filter by categories.

Just interested in use large ip's with ipset to block open proxys or other ip's able to do DDoS attacks.

Just checked https://iplists.firehol.org/ among others and there's just a few and outdated lists about DDoS ip's abusives.

Thank you for you response!
